### ISSUE TITLE
Info request: elk on arm

### ISSUE THREAD

**Issue by pliski** [medcl/pi-warning-light-for-elasticsearch#1]
In the [blog post](https://www.elastic.co/blog/building-a-real-world-alarm-with-elasticsearch-and-raspberry-pi) you said: "We have a small Elasticsearch cluster running on Pi...". 

I'm planning to install an elk stack on my arm board too and I wonder if you can point me in the right direction as the info I've found till know are discouraging: 

- https://discuss.elastic.co/t/compiling-elasticsearch-for-arm/145553/3

- https://discuss.elastic.co/t/arm-support/142235 

Thanks

**Comment by medcl** [comment]
there should be no difference about running es on arm or on other arc.
Pi may be good fit for testing, but for prod environment, it depends.
